### ISSUE TITLE
dataframe utilities could be moved to utils directory

### ISSUE THREAD

**Issue by tmadlener** [key4hep/EDM4hep#102]
As decided during todays meeting, we now have a separate [EDM4Hep-utils](https://github.com/key4hep/EDM4hep-utils) repository. I think the contents of [dataframe](https://github.com/key4hep/EDM4hep/tree/master/dataframe) and the related tests could be moved there.

**Comment by vvolkl** [comment]
Sounds good. Probably also the hepmc tests - a better test of edm4hep is anyway building the whole stack and running the tests in the depending packages (which is what we already do in the nightlies, sans the tests, which will come at one point)

**Comment by tmadlener** [comment]
Since we decided to keep the utilities in the EDM4hep repository instead making a new repository for it, we could consider moving the dataframe related utilities to the utils directory.
