### ISSUE TITLE
Change the edm4hep::Cluster name to be more explicit?

### ISSUE THREAD

**Issue by BrieucF** [key4hep/EDM4hep#104]
I am creating this issue to trigger discussion. While browsing the edm4hep dataformat I realized that the edm4hep::Cluster collection is meant to host calorimeter hits. Don't you think one should change this to a more explicit naming like "CaloCluster" or equivalent? There will soon be the need for other cluster types (e.g. tracker clusters) which will most likely require different member content. Let me know your thoughts...

**Comment by gaede** [comment]
The edm4hep::Cluster is indeed used for calorimeter clusters of hits and is sort of a top level reconstruction object that is typically directly used to form neutral ReconstructedParticles. In that sense is the equivalent to the edm4hep::Track class, used for  charged particles. These names have been used in the linear collider community for more than 15 years and therefore, we would like to keep them as they are. We can easily add more specific cluster like types, e.g. for tracking by adding a suitable prefix to those.
