### ISSUE TITLE
Type difference between EDM4hep and LCIO

### ISSUE THREAD

**Issue by fdplacido** [key4hep/EDM4hep#106]
- EDM4hep version: v00-03 / master

The `algorithmType` for a Vertex is set to type `int` in [EDM4hep](https://github.com/key4hep/EDM4hep/blob/master/edm4hep.yaml#L341). Getting the `algorithmType` for a Vertex in [LCIO](https://github.com/iLCSoft/LCIO/blob/master/src/cpp/include/IMPL/VertexImpl.h#L51) returns a `std::string`, posing a type missmatch between both Vertices on conversion.

**Comment by andresailer** [comment]
* Related to how to store metadata or collection parameters
* Maybe never really used in LCIO
    * Usually store a map of algorithms as collection parameters and refer to the key via the algorithmType (or equivalent)
* --> Keep the int in EDM4hep
