### ISSUE TITLE
TrackState Covariance matrix 

### ISSUE THREAD

**Issue by andresailer** [key4hep/EDM4hep#107]
Replacing: https://github.com/key4hep/k4LCIOReader/issues/8

At the moment the LCIO covariance matrix is lower triangle, while the one in EDM4hep is the upper triangle.

http://lcio.desy.de/v02-09/doc/doxygen_api/html/classEVENT_1_1TrackState.html#a667b8774ce1b0f42dbae11a59dc7e09b

https://github.com/key4hep/EDM4hep/blob/e17d47ab9f17f3a56fb90550d307275cacd93153/edm4hep.yaml#L63

It was decided to change the edm4hep one to lower triangle as well. 

Is there any sane way to prevent existing places where this conversion was done after reading the documentation to not silently break?

**Comment by andresailer** [comment]
For example
https://github.com/key4hep/k4SimDelphes/blob/8561d3fc39b2accc99c62a561090421fad3f1e8e/converter/src/DelphesEDM4HepConverter.cc#L488-L493

**Comment by clementhelsens** [comment]
Hi @andresailer , thanks for deciding :)
As far as I know, this is the only place where the covariance matrix is filled.

**Comment by andresailer** [comment]
I didn't decide this: https://indico.cern.ch/event/1000558/

**Comment by clementhelsens** [comment]
sorry, I misread you comment and missed the "t was" :)
Anyway, this part of the code

https://github.com/key4hep/k4SimDelphes/blob/8561d3fc39b2accc99c62a561090421fad3f1e8e/converter/src/DelphesEDM4HepConverter.cc#L488-L493

will have to be changed once we have properly patched Delphes to get the full matrix.

**Comment by andresailer** [comment]
I should have linked the minutes in the ticket from the start.

The delphes part can already be changed to assume lower triangle though. Still basically makes a mess that there will be files with one and some with a different interpretation.

**Comment by clementhelsens** [comment]
For FCC-ee, I do not think this is problematic. I will anyway remove all the files we have been producing so far for a first clean production where I want to have the full matrix stored, so no show stopper from my side a least!
