### ISSUE TITLE
Diagram is incorrect

### ISSUE THREAD

**Issue by tmadlener** [key4hep/EDM4hep#109]
The [diagram](https://github.com/key4hep/EDM4hep/blob/master/doc/edm4hep_diagram.svg) that is displayed in the github README and at the top of the doxygen documentation is incorrect.

- The `ParticleID` relations should go to the `ReconstructedParticle` instead of the `Cluster`
- The `RecoParticleRef` that is currently here as a workaround for AIDASoft/podio#146 are missing entirely
- The `OneToOneRelation` between `SimTrackerHit` and `MCParticle` should only point from `SimTrackerHit` to `MCParticle`
- The `OneToOneRelation` between `CaloHitContribution` to `MCParticle` should only point from `CaloHitContribution` to `MCParticle`

**Comment by tmadlener** [comment]
Not that we don't have enough to do otherwise, but should we consider, automating the creation of such a diagram. Although, that is more a podio thing than an EDM4Hep thing.

**Comment by vvolkl** [comment]
Good catch! Some comments:

* Both the `Cluster` and the `ReconstructedParticle` have a one-to-many relations to ParicleID, I can add  the missing one  to ReconstructedParticle, but I wouldn't remove it from cluster.
* In my opinion, a two-ended arrow  represents a  `OneToOneRelation` better, even if the information which type actually has ownership is missing. But I'm open to change that.

As for automated diagrams, that's what doxygen is for, no? If you want, go for it of course, but most likely it will take orders of magnitude more time than doing changes manually. However it is true that any future users of podio might benefit.

**Comment by vvolkl** [comment]
Incidentally, I think a larger graphic that also lists the members could be useful as well.

**Comment by tmadlener** [comment]
> - Both the Cluster and the ReconstructedParticle have a one-to-many relations to ParicleID, I can add the missing one to ReconstructedParticle, but I wouldn't remove it from cluster.

Ah you are right, I have missed that this also exists.

> - In my opinion, a two-ended arrow represents a `OneToOneRelation` better, even if the information which type actually has ownership is missing. But I'm open to change that.

Hmm, good point. My main concern would be the distinction to the association data types, which also have bi-directional arrows, and they actually have a reference in both directions.

> Incidentally, I think a larger graphic that also lists the members could be useful as well.

That would be very nice to have indeed. But with that you are finally in the regime where automatic generation would probably be a bit more than just a convenience. However, for now I completely agree that there are more important things to do than coming up with an automatic diagram generation tool. Could be a nice project for a student though maybe.

**Comment by hegner** [comment]
![Digraph gv](https://user-images.githubusercontent.com/1609504/108215808-06200f80-7132-11eb-9b3d-6da5fd1dd6db.png)

gives you the current state of affairs in the relations

**Comment by vvolkl** [comment]
Thanks Benedikt @hegner , that's a very nice addition to the docs!

I think the graphviz image could even be improved and include some of the extra information from the LCIO-style diagram by adding subgraphs for { Monte Carlo | Raw Data | Digitization | Reconstruction and Analysis } and maybe  { Tracking | Calorimeter }. I guess this could be done by adding labels to the types in the yaml, what do you think?

**Comment by hegner** [comment]
@gaede - After checking again, it is indeed only the RecParticleRef missing
