### ISSUE TITLE
Inconsistent get naming for parameters

### ISSUE THREAD

**Issue by fdplacido** [key4hep/EDM4hep#111]
- Package version: v00-03-01

For the Vertex definition, a `VectorMember` of type `float` is defined with name `parameters`.
The resulting code generates a `float getParameters(unsigned int)` that returns a single parameter. The name suggest it would return an array/vector of parameters, which is confusing. It should be renamed to singular or changed to return an array/vector.

```cpp
  unsigned int parameters_size() const;
  float getParameters(unsigned int) const;
  std::vector<float>::const_iterator parameters_begin() const;
  std::vector<float>::const_iterator parameters_end() const;
```

**Comment by tmadlener** [comment]
With the latest changes in podio this should now work more intuitively, because the `podio::RelationRange` object that is returned by e.g. `edm4hep::ParticleID::getParameters()` supports indexed access.

**Comment by tmadlener** [comment]
Closing. Please re-open if the issue persists.
