### ISSUE TITLE
Extend edm4hep::TrackerHit and edm4hep::Track for drift chamber study

### ISSUE THREAD

**Issue by wenxingfang** [key4hep/EDM4hep#124]
Dear experts,

For CEPC drift chamber study, we are exploring the cluster counting method for PID. For cluster counting study, it needs to know the number of primary ionizations per unit length so called dN/dx. In order to use edm4hep::TrackHit and edm4hep::Track for this stduy, we need extend the edm4hep::TrackHit and edm4hep::Track a bit. For edm4hep::TrackHit it needs members about dN(the number of primary ionizations for the hit) and dx(track length for the hit). For edm4hep::Track it need a member about dN/dx. 

Best,
Wenxing

**Comment by gaede** [comment]
Dear @wenxingfang,  as already pointed out in today's meeting, I believe that the TrackerHits should not have a member relating to the dx, as this is a property that can only be assigned after the tracking has run and it's value will depend on the pattern recognition and the strategy chosen for computing the dx. In the TPC dEdx reconstruction for ILD for example (https://github.com/iLCSoft/MarlinReco/blob/master/Analysis/PIDTools/src/Compute_dEdxProcessor.cc) there are several different ways for computing the dx and we never assign the result back to the hit but only compute a mean dEdx for the track. The data member `dedx` in the `TrackerHit` class should not be there really - it is a translation error from the original LCIO TrackerHit, where this member is still in as *deprecated*. I suggest that we remove it from the `TrackerHit`.  Concerning your cluster counting algorithm: as this is is very similar to measuring the energy: could you not store the number of clusters in the `eDep` member ? Or do you measure both ?

**Comment by wenxingfang** [comment]
Dear @gaede ,

Thanks for you comments! So we can do like ILD TPC which does not store dx. For us, we want to measure both number of clusters and deposited energy for hits, and then calculating both dE/dx and dN/dx for each track. Finally, we can compare the PID performance by using dE/dx information and dN/dx information separately. Do you have any suggestions?

**Comment by tmadlener** [comment]
As discussed during the meeting on Aug 23, this is now being prototyped via a datamodel extension and will be merged to edm4hep once the prototype has stabilized.

[minutes](https://indico.cern.ch/event/1192635/?note=208016) (almost at the bottom)

**Comment by wenxingfang** [comment]
Dear @gaede ,
I have checked TPCHit, TrackerRawData, TrackerPulse, TrackerData in LCIO. I think the TrackerData is similar to the DCWaveform. And I have a few questions.
1, does this "_rawArray" in TPCHit has the same meaning as the TrackerRawData ? since they both store raw data
2, the TrackerPulse has 'CovMatrix' which is a vector,  is it important to have this 'CovMatrix'?  Currently, I do not create an EDM for the pulse, the pulse information is contained in the DCRecIonizationCluster, as shown in below. if the vector  'CovMatrix' should be added to a pulse, should I create an EDM for the pulse? otherwise, I don't know how to include the 'CovMatrix' information for each pulse.

  edm4dc::DCRecIonizationCluster:
    Description: "Reconstructed Ionization Cluster"
    Author : "Wenxing Fang, IHEP"
    Members:
       - unsigned long long cellID  //cell id. 
       - float significance         //significance.
       - int type                   //type.
    VectorMembers:
       - float pulseTime            //the pulse's time in the lab frame in [ns].
       - float pulseAmplitude       //the pulse's amplitude.
       - float pulseSignificance    //significance of the pulse.

**Comment by jmcarcell** [comment]
Solved in #179, please reopen if I'm wrong
