### ISSUE TITLE
Take advantage of cmaketools

### ISSUE THREAD

**Issue by hegner** [key4hep/EDM4hep#13]
Instead of adding FindXYZ.CMake files to this project, picking things up from https://github.com/HSF/cmaketools could be useful. This will help with long-term maintenance.

**Comment by vvolkl** [comment]
Makes a lot of sense to me! However, I think first these should be looked at:

https://github.com/HSF/cmaketools/pull/6
https://github.com/HSF/cmaketools/pull/7

**Comment by jmcarcell** [comment]
Closing stale issue, `cmaketools` doesn't seem to be maintained any longer, will reopen if there is interest again
