### ISSUE TITLE
EIC: utility functions for Vector{2,3}{f,d} etc

### ISSUE THREAD

**Issue by wdconinc** [key4hep/EDM4hep#144]
In EIC we have developed several vector utility functions (some using c++20 concepts, but also as legacy) that we would be happy to upstream. In particular, see https://eicweb.phy.anl.gov/EIC/eicd/-/tree/master/utils/include/eicd for vector_utils.h and vector_utils_legacy.h. I am opening this as an issue to start a discussion. We can file a PR following up on this issue after some more discussion.

Primary use cases: calculation of theta, phi, eta from momentum and position vectors stored in the data model.

Alternatives considered: including this in the data model as ExtraCode adds overhead to the yaml description which is not pertinent to the data storage.

Note: because we cannot easily extend the edm4hep data model, we are reimplementing the same edm4hep data model in the eicd namespace. This is not desirable, but at this point in our transition to edm4hep unavoidable.

**Comment by tmadlener** [comment]
Hi @wdoncic, We have started to put some utilities into [utils/include/edm4hep/utils](https://github.com/key4hep/EDM4hep/tree/master/utils/include/edm4hep/utils). Those will in the end be installed into `<prefix>/include/edm4hep/utils` and live in the `edm4hep::utils` namespace. Granted there is not a lot going on in there yet, but we would be very happy to accept additional functionality into that.

I would also be happy to have them with c++20 concepts already, but we will probably need a c++17 compatible version as well for the time being, or at least a version of the concepts that work with gcc8 as well.

**Comment by wdconinc** [comment]
The restricting factor on our side has been the use within ROOT macros, which requires a legacy version anyway (at least until ROOT supports c++20, and even then it will take a while for that to be a reasonable requirement for a user base).
