### ISSUE TITLE
MCParticle::getEnergy may use std::hypot (c++11) for better numerical control

### ISSUE THREAD

**Issue by wdconinc** [key4hep/EDM4hep#145]
Currently https://github.com/key4hep/EDM4hep/blob/master/edm4hep.yaml#L162 defines:
```cpp
      double getEnergy() const { return sqrt( getMomentum()[0]*getMomentum()[0]+getMomentum()[1]*getMomentum()[1]+\n
                                        getMomentum()[2]*getMomentum()[2] + getMass()*getMass()  )  ;}
```
but numerical stability is likely better with
```cpp
      double getEnergy() const { return std::hypot(getMomentum()[0], getMomentum()[1], getMomentum()[2], getMass()); }
```

Other considerations: compatiblity with pre-c++11 would preclude this, and a reimplementation in a utility function could have backwards compatibility implications.

**Comment by tmadlener** [comment]
Since podio already requires at least c++17, I don't think trying to be compatible with pre-c++11 is a concern.

**Comment by hegner** [comment]
I agree. please go on and make a PR. Thanks!

**Comment by andresailer** [comment]
As pointed out in #150, there is no 4 argument hypot, so this is a no-can-do. Closing this issue
