### ISSUE TITLE
Compiling EDM4hep against custom podio in LCG fails to honor `PODIO` environment variable

### ISSUE THREAD

**Issue by wdconinc** [key4hep/EDM4hep#166]
- Goal: I'm attempting to compile EDM4hep in LCG with a more recent version of podio than is present in LCG_101
 - OS version: LCG_101/x86_64-ubuntu2004-gcc9-opt
 - Compiler version: gcc9
 - Package version: ffcdb0b34766e444d145367966037852f7692431
 - Reproduced by (originally inside a GitHub action with [run-lcg-views](https://github.com/AIDAsoft/run-lcg-views)):
```console
#    - name: Build in LCG view
#      uses: aidasoft/run-lcg-view@v1
#      with:
#        release-platform: ${{ matrix.LCG }}
#        run: |

docker run --rm -it -v /cvmfs:/cvmfs:shared ghcr.io/aidasoft/ubuntu2004:latest /bin/bash
source /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-ubuntu2004-gcc9-opt/setup.sh
git clone https://github.com/AIDAsoft/podio
git clone https://github.com/key4hep/edm4hep

          # build podio
          cmake -B podio-build -S podio \
            -DCMAKE_INSTALL_PREFIX=podio-install \
            -DUSE_EXTERNAL_CATCH2=OFF
          make -C podio-build -j6 install
          
          # build EDM4HEP
          export PODIO=$PWD/podio-install
          cmake -B edm4hep-build -S edm4hep \
            -DCMAKE_INSTALL_PREFIX=edm4hep-install \
            -DUSE_EXTERNAL_CATCH2=OFF
          make -C edm4hep-build -j6 install
```
This produces the following output (with the cmake error explained by podio 0.13.0 in `/cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-ubuntu2004-gcc9-opt/include/podio/podioVersion.h`; that's the reason for the custom podio install):
```console
-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found nlohmann_json: /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-ubuntu2004-gcc9-opt/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found suitable version "3.9.1", minimum required is "3.9.1") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found SIO: /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-ubuntu2004-gcc9-opt/include  
-- Found podio: /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-ubuntu2004-gcc9-opt/lib/cmake/podio/podioConfig.cmake  
-- C++ standard: 17
-- Performing Test CXX_FLAG_WORKS__fPIC
-- Performing Test CXX_FLAG_WORKS__fPIC - Success
-- Adding -fPIC to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wall
-- Performing Test CXX_FLAG_WORKS__Wall - Success
-- Adding -Wall to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wextra
-- Performing Test CXX_FLAG_WORKS__Wextra - Success
-- Adding -Wextra to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wpedantic
-- Performing Test CXX_FLAG_WORKS__Wpedantic - Success
-- Adding -Wpedantic to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wno_unused_variable
-- Performing Test CXX_FLAG_WORKS__Wno_unused_variable - Success
-- Adding -Wno-unused-variable to CXX_FLAGS
-- Performing Test CXX_FLAG_WORKS__Wno_unused_parameter
-- Performing Test CXX_FLAG_WORKS__Wno_unused_parameter - Success
-- Adding -Wno-unused-parameter to CXX_FLAGS
-- Detected GNU compatible linker
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-ubuntu2004-gcc9-opt/python/podio_class_generator.py", line 444, in <module>
    gen = ClassGenerator(args.description, args.targetdir, args.packagename, args.iohandlers,
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-ubuntu2004-gcc9-opt/python/podio_class_generator.py", line 68, in __init__
    self.reader.read()
  File "/cvmfs/sft.cern.ch/lcg/releases/podio/00.13-02c84/x86_64-ubuntu2004-gcc9-opt/python/podio_config_reader.py", line 438, in read
    validator.validate(self.components, self.datatypes, self.options.get("exposePODMembers", False))
  File "/cvmfs/sft.cern.ch/lcg/releases/podio/00.13-02c84/x86_64-ubuntu2004-gcc9-opt/python/podio_config_reader.py", line 154, in validate
    self._check_components()
  File "/cvmfs/sft.cern.ch/lcg/releases/podio/00.13-02c84/x86_64-ubuntu2004-gcc9-opt/python/podio_config_reader.py", line 177, in _check_components
    raise DefinitionError("{} defines a member of type '{}' which is not allowed in components"
generator_utils.DefinitionError: a defines a member of type 'int32_t' which is not allowed in components
-- Not adding the ROOT dictionary to the targets because the selection.xml has not been generated
CMake Error at edm4hep/CMakeLists.txt:9 (add_library):
  add_library cannot create ALIAS target "edm4hep::edm4hepDict" because
  target "edm4hepDict" does not already exist.

-- Not adding the SIO Blocks library to the targets because the corresponding c++ sources have not been generated
CMake Error at edm4hep/CMakeLists.txt:19 (install):
  install TARGETS given target "edm4hepDict" which does not exist.

-- Found HepPDT: /cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-ubuntu2004-gcc9-opt/include  
-- Fetching local copy of Catch2 library for unit-tests...
-- Configuring incomplete, errors occurred!
See also "/edm4hep-build/CMakeFiles/CMakeOutput.log".
```

Hinting at the location of podio with the environment variable `PODIO` does not do the job, despite the `find_package(podio REQUIRED HINTS $ENV{PODIO})` at https://github.com/key4hep/EDM4hep/blob/master/CMakeLists.txt#L15. Hinting with `-Dpodio_ROOT=podio-install` fails as well, as does `-Dpodio_DIR=podio-install`.

It appears that in all cases the environment variable `CMAKE_PREFIX_PATH` takes precedence, and only after `unset CMAKE_PREFIX_PATH` is the `PODIO` environment variable honored. However, that causes other packages not to be found (e.g. HepPDT), which are found above.

It would seem that package-specific environment variables should take precedence over general cmake prefix environment variables, and that specific command line definitions should take precedence over all environment variables.

**Comment by tmadlener** [comment]
I am not entirely sure we can do too much here as this is deep in cmake land. In principle the order in which the prefix set is built is described in the [cmake documentation](https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure) (about a page down).

From what I can tell `CMAKE_PREFIX_PATH` is pretty high up the list. What could in principle take precedence is a `podio_DIR` environment variable, a `podio_ROOT` cmake or environment variable. It also mentions that `HINTS` is only looked at after these. 

I am not entirely sure why the `-Dpodio_ROOT` seems to not work as expected in this case as this should be more or less the first thing, unless we run into some cmake policy settings(?).

**Comment by andresailer** [comment]
Why not just prefix the new podio to CMAKE_PREFIX_PATH?

https://github.com/key4hep/EDM4hep/blob/ffcdb0b34766e444d145367966037852f7692431/.github/workflows/lcg_linux_with_podio.yml#L38

Did you try the full-path to podio-install?

**Comment by vvolkl** [comment]
Yes, in the wider stack, the `PACKAGENAME` env vars are actually intended to find data and other misc files and often point to the share dir, I would prefer to stick to standard CMake variables to find things, although I can see how this might be confusing new users.

**Comment by andresailer** [comment]
podio_ROOT (also with relative path) only works if the minimal required version is increased to 3.12 or later

https://github.com/key4hep/EDM4hep/blob/ffcdb0b34766e444d145367966037852f7692431/CMakeLists.txt#L1

or the policy is set https://cmake.org/cmake/help/v3.20/policy/CMP0074.html#policy:CMP0074 to new

**Comment by tmadlener** [comment]
Is there anything that prevents us from bumping this up? How far can we reasonably bump it?

**Comment by vvolkl** [comment]
> > minimal required version is increased to 3.12 or later
> 
> Is there anything that prevents us from bumping this up? How far can we reasonably bump it?

Actually, I recently checked this for  https://github.com/HEP-FCC/FCCAnalyses/pull/189, and there the minimum CMake version is 3.16. For macOS, it's probably 3.19 (https://github.com/root-project/root/blob/master/CMakeLists.txt#L8), but I haven't checked. IMO it makes sense to bump to 3.16.9, and make this somewhat consistent over the stack.

**Comment by andresailer** [comment]
DD4hep is CMake 3.12 for about 3 years, but newer also works

**Comment by tmadlener** [comment]
Just checked Ubuntu 20.04, that comes with 3.16.3 by default
