### ISSUE TITLE
Inconsistent naming of energy deposit in different types

### ISSUE THREAD

**Issue by tmadlener** [key4hep/EDM4hep#180]
Except we have both "EDep" and "eDep" in existing types already...

_Originally posted by @andresailer in https://github.com/key4hep/EDM4hep/pull/179#pullrequestreview-1145216205_

**Comment by andresailer** [comment]
https://github.com/key4hep/EDM4hep/blob/f0d153f698c1ca3ad3c5679931b684eb296ad25e/edm4hep.yaml#L197
https://github.com/key4hep/EDM4hep/blob/f0d153f698c1ca3ad3c5679931b684eb296ad25e/edm4hep.yaml#L313
