### ISSUE TITLE
Python Install Location

### ISSUE THREAD

**Issue by andresailer** [key4hep/EDM4hep#220]
https://github.com/key4hep/EDM4hep/blob/e0762272e0f718df2811fc1bf4590af976bac70d/python/CMakeLists.txt#L1-L4

I think, this, and all the other python, should go to `${CMAKE_INSTALL_LIBDIR}/python${Python_VERSION_MAJOR}.${Python_VERSION_MINOR}/site-packages/edm4hep`

**Comment by jmcarcell** [comment]
But then we would have to change this for every package and also change all the spack recipes, that depending on the version would make PYTHONPATH point to one place or the other. I don't see we gain much when we have a unique python version in the stack and I don't think no one uses those paths instead of PYTHONPATH to search.

**Comment by andresailer** [comment]
But EDM4hep also goes in other places, like the LCG stacks.

(Podio should do the same)

**Comment by jmcarcell** [comment]
So then  is changing the recipes for LCG and spack :skull:
It's just not podio and EDM4hep but every package in key4hep / iLCSoft that has a python installation. I checked in the key4hep builds and basically only python packages follow this convention with a few exceptions. It's unfortunate we don't have a `CMAKE_INSTALL_PYTHONDIR`

**Comment by vvolkl** [comment]
For the spack recipes, you can  just change them to `extends(python)`, similar to how dd4hep does it: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/dd4hep/package.py#L156

**Comment by andresailer** [comment]
LCG stack recipes don't need to change

**Comment by tmadlener** [comment]
Could be a good use case for CMake presets with different defaults?
