### ISSUE TITLE
We should avoid members/relations with the name of a type

### ISSUE THREAD

**Issue by peremato** [key4hep/EDM4hep#247]
The type `edm4hep::SimTrackerHit` has the relation to the originating`MCParticle` called `MCParticle`.  I think this is not a very good idea:
- data members should be lowercase (at least start with lowercase)
- having the data member the same as the class name is very confusing

``` 
#----------- SimTrackerHit
  edm4hep::SimTrackerHit:
    Description: "Simulated tracker hit"
    Author: "F.Gaede, DESY"
    ...
    OneToOneRelations:
      - edm4hep::MCParticle MCParticle //MCParticle that caused the hit. 
    ...
```

**Comment by gaede** [comment]
I fully agree that member names should be lowercase and not be the same as class names. However, I think this is only true for the generated code and there we are fine, as a `get` is prepended here:
```
  /// Access the MCParticle that caused the hit.
  const edm4hep::MCParticle getMCParticle() const;
```

**Comment by peremato** [comment]
Yes, but in other languages like Julia we do not generate all these non-sense accessors :-) See for example: 
https://github.com/peremato/EDM4hep.jl/blob/main/podio/genDatatypes.jl

**Comment by hegner** [comment]
That's a matter of language, not us wanting these explicit accessors. Constness/immutability is one of the things which we don't have for free here for example. 
Otherwise I agree on the naming - seems we missed the inconsistency here.
