### ISSUE TITLE
`TPCHit` too specific?

### ISSUE THREAD

**Issue by vvolkl** [key4hep/EDM4hep#25]
The content of [`TPCHit`](https://github.com/HSF/EDM4hep/blob/add_ReconstructedParticle/edm4hep.yaml#L283) is maybe useable for more detector types - could consider renaming.

**Comment by tmadlener** [comment]
As per the discussion in the [EDM4hep meeting](https://indico.cern.ch/event/1204616/) (Oct. 18, 2022) this should be renamed to `TrackerRawData`.

@wenxingfang do you want to do this as part of #179, or should we rather make a separate pull request for it?

**Comment by wenxingfang** [comment]
I can do it in https://github.com/key4hep/EDM4hep/pull/179. :)
