### ISSUE TITLE
Homogenize the authors of the datatypes?

### ISSUE THREAD

**Issue by tmadlener** [key4hep/EDM4hep#255]
Currently all the datatypes effectively have the person who put the definition of the yaml file as author. I would propose to put a generic *Key4hep authors* or *EDM4hep authors* there as in general the definition has been discussed and agreed upon by the whole group.

**Comment by gaede** [comment]
Very good idea. Maybe we could add a an authors files w/ main authors and contributers as well ?

**Comment by tmadlener** [comment]
Yes sounds good. Would also make zenodo integration easier, I think.
