### ISSUE TITLE
The conversion operator is not being used in python to go from Mutable to the non-mutable type

### ISSUE THREAD

**Issue by jmcarcell** [key4hep/EDM4hep#270]
For example, the following code will fail:
``` python
import podio
import edm4hep
particles = edm4hep.MCParticleCollection()
parent_particle = particles.create()
daughter_particle = particles.create()
parent_particle.addToParents(daughter_particle)
```

with the error:
```
TypeError: void edm4hep::MutableMCParticle::addToParents(edm4hep::MCParticle) =>
    TypeError: could not convert argument 1
```

However if one does interactively `daughter_particle.operator<TAB>` it will get expanded to 
```daughter_particle.operator MCParticle```
 but with a space in between it's not valid syntax. We can try: 
```daughter_particle.__getattribute__('operator MCParticle')()```
 but this doesn't work either.

There is a workaround for this:

``` python
import cppyy.ll
...
    parent_particle.addToParents(cppyy.ll.cast['edm4hep::MCParticle'](daughter_particle))
```
(`static_cast` can also be used, `cast` is simply a C-like cast)

More information about operators in cppyy: https://cppyy.readthedocs.io/en/latest/classes.html#operators and https://cppyy.readthedocs.io/en/latest/type_conversions.html#operators

It looks to me this is something on the cppyy side, that the cppyy wrapped objects won't convert automatically since we have seen that when we cast ourselves the operator works fine.

**Comment by tmadlener** [comment]
Yes, that is definitely a good idea regardless. Another issue might be that the cppyy that comes with ROOT could not be the latest version of cppyy.

**Comment by jmcarcell** [comment]
Ugh the version from ROOT is almost 4 years old...: https://github.com/wlav/cppyy/releases/tag/cppyy-1.6.2

**Comment by m-fila** [comment]
Conversion function doesn't work with the newest standalone cppyy either:

```python
>>> import cppyy
>>> import cppyy.ll
>>> cppyy.__version__
'3.1.2'
>>> cppyy.cppdef("""
... 
... namespace ns {
... struct To{};
... 
... struct From{
...     operator To() const {return To();} 
... };
... 
... int foo(const To&) {return 0;}
... 
... }""")
True
>>> f = cppyy.gbl.ns.From()
>>> foo = cppyy.gbl.ns.foo
>>> foo(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: int ns::foo(const ns::To&) =>
    TypeError: could not convert argument 1

```

**Comment by jmcarcell** [comment]
Thanks for checking. That was my fear yesterday when I checked in issues and PRs and there was nothing about conversion operators... Now it's reported to cppyy

**Comment by m-fila** [comment]
Not sure if acceptable in edm4hep and podio context but adding a converting constructor seems to make it work in both new and older cppyy

```python
>>> import cppyy
>>> cppyy.__version__
'1.6.2'
>>> cppyy.cppdef("""
... 
... namespace ns {
... class From;
... 
... struct To{
...  To() = default;
...  explicit To(const From&) {}
... };
... 
... struct From{
...     operator To() const {return To();} 
... };
... 
... int foo(const To& ) {return 0;}
... 
... }""")
True
>>> f = cppyy.gbl.ns.From()
>>> foo = cppyy.gbl.ns.foo
>>> foo(f)
0

```

**Comment by tmadlener** [comment]
I think from a c++ point of view it shouldn't really matter, right? In the end, having a converting constructor (even with `explicit`) and having a conversion operator should be the same? :thinking:

**Comment by m-fila** [comment]
Should be fine, unless there are some corner cases. I'll check it
