### ISSUE TITLE
Missing methods in doxygen documentation for `CovMatrix` classes

### ISSUE THREAD

**Issue by m-fila** [key4hep/EDM4hep#296]
In `CovMatrix` classes the members declared with `#include <edm4hep/detail/CovMatrixCommon.ipp>` don't appear in documentation generated with doxygen. For instance `operator[]`, `getValue` and `setValue` are missing. 

Doxygen is doing some limited preprocessing and apparently doesn't resolve correctly `#include` directives inside `{ }`.

https://github.com/key4hep/EDM4hep/blob/f46cf67f39d5d4b587e08359786d808a1c5c8ea3/edm4hep.yaml#L130-L138

![missing methods](https://github.com/key4hep/EDM4hep/assets/37295697/91d0ccd2-98ab-49ba-b71c-d3e138d2d8a1)

**Comment by tmadlener** [comment]
I tried a few knobs and I can get the `CovMatrixCommon.ipp` header to end up in the documentation, but it does indeed not seem possible to have them end up in the class this way.

What could be done would be to have a general `CovMatrix` page that we could link to, as we do, e.g. for the [`PIDHandler`](https://edm4hep.web.cern.ch/classedm4hep_1_1utils_1_1_p_i_d_handler.html) that links to a more indepth description.

**Comment by m-fila** [comment]
Perhaps some directive could be added to podio generator to paste contents of local files in declarations. But it's probably an overkill since the only problem here is minor annoyance with documentation

**Comment by tmadlener** [comment]
In principle something like this was planned at some point: https://github.com/AIDASoft/podio/blob/bde3830b321d6f6c0508d7d4d6e19cc1b7b3efab/python/podio_gen/podio_config_reader.py#L175-L176

It would make the generated code much easier to read as well, as people will not have to go hunt for an include somewhere.

**Comment by tmadlener** [comment]
Opening this again, since #308 will be the one that actually fixes this.

**Comment by hegner** [comment]
Ah. I sometimes hate automatic closing actions of GitHub (most of the time useful though ;-) )
