### ISSUE TITLE
`RawTimeSeries` is not connected to the rest of EDM4hep

### ISSUE THREAD

**Issue by tmadlener** [key4hep/EDM4hep#316]
`RawTimeSeries` is not referenced in any relation of another datatype in EDM4hep. Hence, it is effectively unconnected to the rest of EDM4hep This is very similar to the situation for the `RawCalorimeterHit` (see #317). Its definition is

https://github.com/key4hep/EDM4hep/blob/bd9f45039149781a9c54799a6d03df56b1b5ed49/edm4hep.yaml#L519-L529

The `RawTimeSeries` originally was the `TPCHit` (as also found in [LCIO](https://github.com/iLCSoft/LCIO/blob/master/src/cpp/include/pre-generated/EVENT/TPCHit.h)) and was renamed in https://github.com/key4hep/EDM4hep/pull/179. In this PR the `rawDataWords` from LCIO was also renamed into `adcCounts`.

The closest related datatype that is related to something in EDM4hep is the `TimeSeries`

https://github.com/key4hep/EDM4hep/blob/bd9f45039149781a9c54799a6d03df56b1b5ed49/edm4hep.yaml#L760-L769

In LCIO the `TrackerHit` has a [`getRawHits`](https://github.com/iLCSoft/LCIO/blob/384e6dcc591a123669b9933b58008019a0d4c82d/src/cpp/include/pre-generated/EVENT/TrackerHit.h#L84-L87) method to which effectively arbitrary LCIO datatypes can be attached (thanks to inheritance from `LCObject`). This mechanism is no longer present in EDM4hep. Hence, some "untyped" relations are not possible in EDM4hep.

We need to decide whether we want to keep the `RawTimeSeries` as it is, or whether we simply drop it from EDM4hep and declare another (non-raw) datatype as "entry point" to EDM4hep (coming from the detector reconstruction side).

**Comment by gaede** [comment]
We (BH, JMC, FG) suggest to drop the `RawTimeSeries` for now. (Only add/keep if we find current code that uses it).

**Comment by tmadlener** [comment]
@mirguest can you check if / where this is used on the CEPC side?

**Comment by tmadlener** [comment]
Also used in dual-readout: https://github.com/HEP-FCC/dual-readout/blob/51f9766bb3f9e80644bb032b98f1f5b1d4cb0327/DRsim/DRsimG4Components/include/SimG4SaveDRcaloHits.h#L34

**Comment by tmadlener** [comment]
Keeping it as it is currently used. Consider adding an `Association` to something else on request when necessary.
