### ISSUE TITLE
`RawCalorimeterHit` is not connected to the rest of EDM4hep

### ISSUE THREAD

**Issue by tmadlener** [key4hep/EDM4hep#317]
`RawCalorimeterHit` is not referenced in any relation of any datatype in EDM4hep. Hence, it is effectively unconnected to the rest of EDM4hep. This is similar to the situation with `RawTimeSeries` (see https://github.com/key4hep/EDM4hep/issues/316). The definition of the `RawCalorimeterHit` is

https://github.com/key4hep/EDM4hep/blob/bd9f45039149781a9c54799a6d03df56b1b5ed49/edm4hep.yaml#L395-L401

The datatype that probably has the closest resemblance with the `RawCalorimeterHit` is the `CalorimeterHit`, defined as
https://github.com/key4hep/EDM4hep/blob/bd9f45039149781a9c54799a6d03df56b1b5ed49/edm4hep.yaml#L404-L413

Historically, the `RawCalorimeterHit` is present because it's also present in [LCIO](https://github.com/iLCSoft/LCIO/blob/master/src/cpp/include/pre-generated/EVENT/RawCalorimeterHit.h) and the fact that the `CalorimeterHit` has an untyped [`getRawHit`](https://github.com/iLCSoft/LCIO/blob/384e6dcc591a123669b9933b58008019a0d4c82d/src/cpp/include/pre-generated/EVENT/CalorimeterHit.h#L79-L82) in LCIO where it could in principle be attached. However, this mechanism doesn't exist in EDM4hep.

We have to decide whether we want to keep the `RawCalorimeterHit` in EDM4hep or whether we want to remove it and declare the (calibrated) `CalorimeterHit` as entry point for reconstruction in EDM4hep.

**Comment by gaede** [comment]
We (BH, JMC, FG) suggest to drop the `RawCalorimeterHit` for now.  (Only add/keep if we find current code that uses it).

**Comment by jmcarcell** [comment]
This is used in the dual-readout repo: https://github.com/HEP-FCC/dual-readout/blob/master/DRsim/DRsimG4Components/include/SimG4SaveDRcaloHits.h#L33
