### ISSUE TITLE
`radiusOfInnerMostHit` could be removed from `Track`

### ISSUE THREAD

**Issue by tmadlener** [key4hep/EDM4hep#319]
The `Track` currently has a member `radiusOfInnerMostHit`, which could be removed, as it is technically easily computable from the attached `TrackerHit`s. The only / main(?) reason to keep it would be to keep this information around even if the `TrackerHit`s are dropped (as is the case for example in DSTs for ILD).

**Comment by gaede** [comment]
We (BH, JMC, FG) believe that this should be droped.  (If really needed later, adding it is easy w/ schema evolution).

**Comment by Zehvogel** [comment]
This was quite useful information on DST files (no-hits) imo...

**Comment by tmadlener** [comment]
Removing it for now, since it's mixing analysis and reconstruction level quantities too much. We have a similar discussion for other items, e.g. #322

**Comment by andresailer** [comment]
Dear @farakiko 

Please open a new issue, and please don't screenshoot text, but give us the actual code as text so we don't have to potentially type things ourselves.

Thanks,
Andre

**Comment by farakiko** [comment]
Thank you! Submitted the issue [here](https://github.com/key4hep/EDM4hep/issues/384).
