### ISSUE TITLE
`RecoParticleVertexAssociation` duplicates relation information

### ISSUE THREAD

**Issue by tmadlener** [key4hep/EDM4hep#321]
Somewhat related to the discussion in #320 but then again separate enough to warrant a dedicated issue. The currently existing `RecoParticleVertexAssociation` is in principle superfluous, as it connects `Vertex` and `ReconstructedParticle`; a connection that already exists with internal relations of the two datatypes

https://github.com/key4hep/EDM4hep/blob/bd9f45039149781a9c54799a6d03df56b1b5ed49/edm4hep.yaml#L680-L687
`ReconstructedParticle`:
https://github.com/key4hep/EDM4hep/blob/bd9f45039149781a9c54799a6d03df56b1b5ed49/edm4hep.yaml#L591-L592
`Vertex`:
https://github.com/key4hep/EDM4hep/blob/bd9f45039149781a9c54799a6d03df56b1b5ed49/edm4hep.yaml#L563-L564

Or in pictures:
![image](https://github.com/key4hep/EDM4hep/assets/16774861/fedc6ccb-4cf1-4d6e-b80f-fb6dd68478b1)

Historically the existence of this associations seems to be caused by the fact that something in iLCSoft in either the ILD or CLIC reconstruction(?) creates an `LCRelation` between a `Vertex` and `ReconstructedParticle`, which then required this association during the conversion between EDM4hep and LCIO. The main culprit is most likely [LCFIPlus](https://github.com/lcfiplus/LCFIPlus/blob/39cf1736f3f05345dc67553bca0fcc0cf64be43e/src/LCIOStorer.cc#L954) and another one is [here](https://github.com/iLCSoft/MarlinReco/blob/4ee55bd4b42a3d31758769954e6735aadc54e940/Analysis/SLDCorrection/src/SLDCorrection.cc#L1311-L1316).

I am currently not entirely sure whether it's easily possible to remove this.

**Comment by gaede** [comment]
We (BH, JMC, FG) suggest to keep it, following our proposal in #320 to not have the link to vertex in the RecoParticle.

**Comment by tmadlener** [comment]
Keep this regardless of the decision in #320, because we need this to keep information about the start vertex.
