### ISSUE TITLE
Wrong intended assignment of CovMatrix in createEDM4hepFile.py

### ISSUE THREAD

**Issue by peremato** [key4hep/EDM4hep#355]
With the following line, the output file is written with 21 zeros instead of the intended value of `cov6f`.
https://github.com/key4hep/EDM4hep/blob/7ffc2d4ec39842e8a69cce5430f6c7489c47d517/scripts/createEDM4hepFile.py#L228

I guess it should be `state.setCovMatrix(cov6f)`

**Comment by tmadlener** [comment]
I think it should also work with `state.covMatrix`

**Comment by peremato** [comment]
Have a look at what is stored. If I remember correctly I was getting a covmatrix fill with zeros. See the TBrowser output:
![Uploading Screenshot 2024-09-02 at 10.43.05.png…]()

**Comment by jmcarcell** [comment]
Yes, this will be fixed in https://github.com/key4hep/EDM4hep/pull/353
