### ISSUE TITLE
always use #include "edm4hep/*.h"

### ISSUE THREAD

**Issue by andresailer** [key4hep/EDM4hep#38]
While the header files are installed to `<install_dir>/edm4hep` the include statements for the edm4ep headers usually does not include the edm4hep prefix, thus forcing one to add the edm4hep directory in the include directories.  We risk running into clashes, especially for files like Vector3f

I think it would be better if that were not necessary, but I don't know where to fix that in the code generation.

PS: we should also consider adding an edm4hep "namespace" to the include guards.
(Whats the problem with `#pragma once` ?)

**Comment by vvolkl** [comment]
Good point. I don't think there is any argument against `#pragma once` for our usecase.

**Comment by graeme-a-stewart** [comment]
Just a comment that the C++ experts in ATLAS were rather against `#pragma once` as it's not actually a standard.

In addition, the oft quoted speed increase doesn't apply for modern compilers, which optimise away second and subsequent file opens of headers.

**Comment by andresailer** [comment]
(https://en.wikipedia.org/wiki/Pragma_once#Caveats)
It would, however, prevent `#define` clashes. (for podio/ObjectID.h and edm4hep/ObjectID.h these only differ in case at the moment).
Though, after having a bit more knowledge of podio AIDASoft/podio#70 , I think it is straight forward to add a "namespace" to the defines.
