### ISSUE TITLE
[Build Infrastructure] Update with Upstream Improvements

### ISSUE THREAD

**Issue by vvolkl** [key4hep/EDM4hep#4]
https://github.com/AIDASoft/podio/pull/54 should allow us to clean up the cmake configuration.

See also the discussion here:
https://github.com/HSF/EDM4HEP/pull/1

**Comment by gaede** [comment]
Partly addressed in #7 - I am sure there is still room for improvement in how the cmake is organized. In particular it would be nice to have a make command for regenerating the EDM ...

**Comment by drbenmorgan** [comment]
> In particular it would be nice to have a make command for regenerating the EDM ...

That's something I looked at way back, but I think it's possible using the techniques outlined here:

https://here-be-braces.com/integrating-a-flexible-code-generator-into-cmake/

Given that `file(GLOB ...)` is used to gather the sources, adding a line before their generation:

```cmake
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS edm4hep.yaml)

execute_process(COMMAND python ${podio_CMAKE_DIR}/../python/podio_class_generator.py edm4hep.yaml edm4hep edm4hep
                WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
```

should trigger a re-cmake and thus regeneration if `edm4hep.yaml` changes (but see the caveats at the end of the article especially on cleaning old files). I don't think there's a way to avoid a re-run of `cmake`, but at least it is triggered automatically.

**Comment by gaede** [comment]
That would be nice to have - and a re-run of the cmake would be no problem at all.

**Comment by vvolkl** [comment]
As far as I can tell, these issues have all been adresse.
