### ISSUE TITLE
HepMC3 support

### ISSUE THREAD

**Issue by tmadlener** [key4hep/EDM4hep#60]
Currently it seems that only `HepMC` up to version `2.06.10` is supported for the integration tests. Trying to build using `HepMC3` leads to several issues that are related to [differences between `HepMC` and `HepMC3`](http://hepmc.web.cern.ch/hepmc/differences.html).

Should we update to `HepMC3` (and state so in the documentation) as `HepMC` will no longer receive updates, or should we try and keep both versions for the integration tests?

The easiest way out is to update the documentation to make it explicit that the tests depend on `HepMC` and not `HepMC3`.

**Comment by vvolkl** [comment]
A converter for HepMC3 would be great to have in EDM4hep! Since 2/3 are not compatible, but 2 is still widely used, my opinion is that we should support both, but only be an optional dependency for a converter and corresponding tests.

**Comment by andresailer** [comment]
I think @tmadlener's question was about the test, and if that should just be explicit to request HepMC(2) and just not build with HepMC3, or if the test should be changed to use HepMC3 and not build with HepMC2?

**Comment by tmadlener** [comment]
In principle it is a pretty open question from my side. For now, the most important thing would probably to explicitly document that the test has to be built with HepMC and will not build with HepMC3.

However, on a slightly longer timescale also converters would be great to have. Then both versions will probably have their own small tests that will be built alongside them in any case, right?

**Comment by andresailer** [comment]
The HepMC3 readerfactory can also read hepmc2 ascii files. So unless an in memory translation from the HepMC2 objects is needed, it would be enough to just use HepMC3 in EDM4hep.

**Comment by vvolkl** [comment]
@andresailer Agreed, HepMC3 only seems fine, in practice there won't be too many conversions anyway, I believe.

The CMake configuration is currently ok, though. In order to use HepMC3 one has to explicitly use `find_package(HepMC3)`, so it cannot pick up HepMC3 by accident. You had to change that in `tests/CMakeLists.txt`, right @tmadlener? However we can add a line to the readme  to clarify that HepMC2 is not HepMC3, or immediately add a converter for HepMC3.

**Comment by vvolkl** [comment]
Ah,  I just checked - with HepMC version 3.0.0 this was indeed possible, but with versions newer 3.1.0 the HepMC Config file has been renamed to include 3. I'll see if I can find a fix.

**Comment by tmadlener** [comment]
> The CMake configuration is currently ok, though. In order to use HepMC3 one has to explicitly use `find_package(HepMC3)`, so it cannot pick up HepMC3 by accident. You had to change that in `tests/CMakeLists.txt`, right @tmadlener? However we can add a line to the readme to clarify that HepMC2 is not HepMC3, or immediately add a converter for HepMC3.

Yes exactly. However, that just makes CMake pick up `HepMC3` correctly. After that compiling fails because the namespace is now `HepMC3` instead of `HepMC` and other changes that would require more work to actually make everything compile again.
