### ISSUE TITLE
ReconstructedParticle Energy is 0 for charged particles

### ISSUE THREAD

**Issue by clementhelsens** [key4hep/EDM4hep#86]
I noticed that when running delphesPythia8_EDM4HEP, charged particles in the ReconstructedParticle collection have a energy set to 0. The momentum is fine though.
I used the IDEA track Cov delphes card for this test, did not tried with an other card.

**Comment by tmadlener** [comment]
Hi @clementhelsens,
Does the corresponding Delphes output have non-zero energy in this case? In principle we do 
```cpp
cand.setEnergy(delphesCand->Momentum.E());
```
for all ReconstructedParticles, regardless of whether they are based on a Track or a Tower in Delphes.

**Comment by clementhelsens** [comment]
Hi @tmadlener , 

yes, I see this is the code.
In delphes it seems not to be an issue.
What I don't understand is at which level the information is taken. For example, for the EFlowTrack, this is the name in the Delphes TreeWritter, but the collection name is Calorimeter/eflowTracks.

**Comment by tmadlener** [comment]
So after checking again; The changes that fill the energy of the reconstructed particles have only been introduced in #79. This also means that the `v00-02` tag does **not** yet have these changes applied and does not fill the reconstructed particle energy.

This should be fixed with a new version.

**Comment by vvolkl** [comment]
Yes - I propose to merge the current PR and then to make a tag.

**Comment by vvolkl** [comment]
@clementhelsens I just installed `key4hep-stack@2020-10-14` which includes today's edm4hep tag and updated the symlink. Let me know if we can close.

**Comment by clementhelsens** [comment]
@vvolkl , I checked that the energy for charged particles in the latest installation is not 0. I'll close the issue
