### ISSUE TITLE
gh-pages branch inflates repository size

### ISSUE THREAD

**Issue by vvolkl** [key4hep/EDM4hep#99]
This is currently about 100M (due to a large number of images) which gets downloaded on every clone (unless `--single-branch` is used). Possible solutions:

* shrink the size of the doxygen page
* host the gh-pages branch on a separate repository (changes the url)
* host the html files on eos (requires a mirror to gitlab and a web deployment ci job, changes the url)

**Comment by andresailer** [comment]
Maybe using git submodule to move the github pages to a different 
repository could work more transparently?

https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/using-submodules-with-github-pages

Then one would only get the github pages with "git clone --recursive", this could of course come back to bite one eventually.

**Comment by vvolkl** [comment]
Fixed in #105 by deploying directly to cern.ch/edm4hep
